// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PcrPhone struct {
	ID          int32
	Model       pgtype.Text
	Mac         pgtype.Text
	Username    pgtype.Text
	Password    pgtype.Text
	DisplayName pgtype.Text
}
